### ISSUE TITLE
Update all logos on teal.gallery home & demo page

### ISSUE THREAD

**Issue by telepath37** [insightsengineering/teal.gallery#71]
@donyunardi 

Please can we get this done asap? We need to work on the NEST promo video and there will be screen recording using the teal.gallery site.

Feel free to grant access to any coredev member of the new logos.

**Comment by donyunardi** [comment]
Sure, I'll prioritize this.

### Task: 
- [ ] Update NEST icon in home page (make sure favicon also update). Use dynamic URL so we can point the image from the hex-sticker repo
- [ ] Update all apps with update NEST logo (same thing, favicon).
- [ ] Re-record all GIF with updated NEST logo and upload to repo.

**Comment by donyunardi** [comment]
The teal.gallery website is updated but I don't see the apps are updated.
I thought pushing to main will automatically start some workflow to merge main to deploy-apps@main but I don't think the case.

I will create PR to merge main t0 deloy-apps@main.

**Comment by donyunardi** [comment]
Yupe, that does it.
Apps are being deployed:
https://github.com/insightsengineering/teal.gallery/actions/runs/6193771768

**Comment by donyunardi** [comment]
everything deployed. Double check a few and it looks good.
